# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corto', '0002_remove_urls_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corto.Urls')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corto.User')),
            ],
        ),
    ]
