# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corto', '0003_user_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_token', models.CharField(max_length=1000)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corto.Urls')),
            ],
        ),
    ]
