# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corto', '0005_urls_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('urlId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corto.Urls')),
            ],
        ),
    ]
